### ISSUE TITLE
Test a11y

### ISSUE THREAD

**Issue by ai** [evilmartians/oklch-picker#13]
Test tools with screen reader and then ask a friend who really use screen reader for integration testings

**Comment by AleksandrSl** [comment]
Excuse me for breaking in.

Tried a little with orca on fedora. 

Some moments: 
* links for personal socials could contain info about the platform?
* links in the description are very vague. Not sure how real screen reader users would use them, but hearing `"were created" link` gives no context. Though reading the whole text adds this context.
* keyboard shortcut is read when you focus input field, ~~but label is not~~, so we got "c 0.205". Took a look at the code, `c` is an actual label, maybe the full name will be better?
* it says invalid entry for all inputs with numbers, orca bug?
* setting don't pronounce the state they are in, so just "show graphs". there is also no way to change that value from the keyboard? Though settings are actually not needed for users with screenreaders, because they only affects charts.
* keyboard shortcuts overlaps with screenreader shortcuts, e.g. c is for comboboxes in orca, h for headers.

Some general thoughts:
* icons are usually hidden via `aria-hidden=true` to prevent screenreader from reading 'image'. Orca doesn't do this, but I'm not sure for other readers.
* contrast of keyboard shortcuts, it was a battle to see whether it's an `i` or `r` on the first input, though I don't have such bad vision :sweat_smile: 
* having links without href is bad, because it can confuse some screenreaders (proofs needed), anyway it's not treated as a link by most screenreaders, so could be rendered as span. Or a link with [aria-current](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current).
* Maybe we need some description how color picker works for screenreaders, when you see the buttons and charts it's easier, that just hearing headers with inputs

What is the purpose of `aria-live="polite" aria-label="Benchmark" aria-hidden="true"` of aria attributes on hidden element is it in development?

**Comment by AleksandrSl** [comment]
By the way, system theme is working in firefox, and that's great!

**Comment by ai** [comment]
Fixed checkbox a11y 5625d66
