### ISSUE TITLE
Any future plan on supporting Adobe RGB?

### ISSUE THREAD

**Issue by cvopisso** [evilmartians/oklch-picker#135]
As the title suggests, I'm using Adobe RGB with my daily driving monitor instead of P3. So I'm glad to see this amazing tool can work with this color space used by many artists and graphic designers.

**Comment by ai** [comment]
We are not planning to do so, because this tool is focused on web and iOS development, and we don’t have Adobe RGB there.

Another problem is that Adobe RGB is RGB color space, not hue-saturation-lightness. This is why the whole UI will not work.

But we can add Adobe RGB output if you can explain how you are planning to use it.
