### ISSUE TITLE
Add math to L, C, H fields

### ISSUE THREAD

**Issue by ai** [evilmartians/oklch-picker#74]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/19343/219353750-2a54078b-b99b-4941-abdd-5d6584df3535.png">

**Comment by raidenmiro** [comment]
Hi @ai! I would like to help with this and send pr. But I have a few questions. The use of operators is invalid for an input with the type `number`. Therefore `event.target.value` returns an empty string. Is there any way to get values with operators without changing the type, or to change the input type to `string` and perform validation via js?

**Comment by ai** [comment]
Try to use `input` event to get the value before trimming.

Also, maybe `novalidate` can help.

Re-emulating `type=number` can be hard: we need `↑`/`↓` buttons, numbers keyboard on mobile (can be done by `inputmode`), changing values by pressing <kbd>↑</kbd>/<kbd>↓</kbd> and validation.

**Comment by raidenmiro** [comment]
Which operations should we support? For example, the basic operations `-`, `+`, `/`, `*`, or only `+`, `-`, that can be used in the input with type `number`?

**Comment by ai** [comment]
Let's start from basics.

The research is part of this task.

**Comment by raidenmiro** [comment]
After several attempts, I came to the conclusion. Why do I whink the native `input=number` is not suitable. Because firstly, it does not support operators such as `* /`.

Second, even if it were possible to support only `- +` operations, it would be difficult to save the value of the field into a variable during the `input` event, we have no way of knowing at what position the user will start entering a new character. (`input.selectionStart` is not included in `input=number` [spec](https://html.spec.whatwg.org/multipage/input.html#do-not-apply)).

I wrote a simple implementation to emulate `input=number` to support the basic operations `+`, `-`, `/`, `*`. [Reproduce](https://codesandbox.io/s/cold-currying-is3ngc).

A few questions also remain. 

What to do when run `increase` (`decrease`) when an expression is entered, example `20+20`.

How to validate input data, leave more freedom of choice allowing numbers, supported operators. Otherwise, allow to print the next character depending on the last one. Some `fsm` pattern.

|last char|  possible next char |
|---------|---------------------|
| Number  |  Number, Operator   |
|Operator |  Number             |
| Another |                     |

**Comment by romashamin** [comment]
@raidenmiro the implementatin in the sandbox looks perfect, thank you!

**Comment by romashamin** [comment]
@ai what are we waiting for? 😊
